//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumManagementApp.Client.TaskService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskService.ITaskService")]
    public interface ITaskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/AddTask", ReplyAction="http://tempuri.org/ITaskService/AddTaskResponse")]
        void AddTask(ScrumManagementApp.Common.DTOs.TaskDTO taskDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/AddTask", ReplyAction="http://tempuri.org/ITaskService/AddTaskResponse")]
        System.Threading.Tasks.Task AddTaskAsync(ScrumManagementApp.Common.DTOs.TaskDTO taskDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/GetTasksForUserStory", ReplyAction="http://tempuri.org/ITaskService/GetTasksForUserStoryResponse")]
        System.Threading.Tasks.Task[] GetTasksForUserStory(int userStoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/GetTasksForUserStory", ReplyAction="http://tempuri.org/ITaskService/GetTasksForUserStoryResponse")]
        System.Threading.Tasks.Task<System.Threading.Tasks.Task[]> GetTasksForUserStoryAsync(int userStoryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskServiceChannel : ScrumManagementApp.Client.TaskService.ITaskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskServiceClient : System.ServiceModel.ClientBase<ScrumManagementApp.Client.TaskService.ITaskService>, ScrumManagementApp.Client.TaskService.ITaskService {
        
        public TaskServiceClient() {
        }
        
        public TaskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddTask(ScrumManagementApp.Common.DTOs.TaskDTO taskDTO) {
            base.Channel.AddTask(taskDTO);
        }
        
        public System.Threading.Tasks.Task AddTaskAsync(ScrumManagementApp.Common.DTOs.TaskDTO taskDTO) {
            return base.Channel.AddTaskAsync(taskDTO);
        }
        
        public System.Threading.Tasks.Task[] GetTasksForUserStory(int userStoryId) {
            return base.Channel.GetTasksForUserStory(userStoryId);
        }
        
        public System.Threading.Tasks.Task<System.Threading.Tasks.Task[]> GetTasksForUserStoryAsync(int userStoryId) {
            return base.Channel.GetTasksForUserStoryAsync(userStoryId);
        }
    }
}
